<?php

/**
 * Lotestrxtmp
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-08-06, 21:14:21
 */
class Lotestrxtmp extends \Phalcon\Mvc\Model {

// **********************
// ATTRIBUTE DECLARATION
// **********************


    protected $TxnLineID;
    protected $TimeCreated;
    protected $TimeModified;
    protected $EditSequence;
    protected $TxnDate;
    protected $RefNumber;
    protected $ItemRef_ListID;
    protected $ItemRef_FullName;
    protected $Memo;
    protected $MemoTrx;
    protected $NumeroTrx;
    protected $FechaTrx;
    protected $TipoTrx;
    protected $OrigenTrx;
    protected $DestinoTrx;
    protected $OrigenDesc;
    protected $DestinoDesc;
    protected $QtyTrx;
    protected $Name;
    protected $Sales_Desc;
    protected $Disponible;
    protected $Estado;

// **********************
// GETTER METHODS
// **********************


    function getTxnLineID() {
        return $this->TxnLineID;
    }

    function getTimeCreated() {
        return $this->TimeCreated;
    }

    function getTimeModified() {
        return $this->TimeModified;
    }

    function getEditSequence() {
        return $this->EditSequence;
    }

    function getTxnDate() {
        return $this->TxnDate;
    }

    function getRefNumber() {
        return $this->RefNumber;
    }

    function getItemRefListID() {
        return $this->ItemRef_ListID;
    }

    function getItemRefFullName() {
        return $this->ItemRef_FullName;
    }

    function getMemo() {
        return $this->Memo;
    }

    function getMemoTrx() {
        return $this->MemoTrx;
    }

    function getNumeroTrx() {
        return $this->NumeroTrx;
    }

    function getFechaTrx() {
        return $this->FechaTrx;
    }

    function getTipoTrx() {
        return $this->TipoTrx;
    }

    function getOrigenTrx() {
        return $this->OrigenTrx;
    }

    function getDestinoTrx() {
        return $this->DestinoTrx;
    }

    function getOrigenDesc() {
        return $this->OrigenDesc;
    }

    function getDestinoDesc() {
        return $this->DestinoDesc;
    }

    function getQtyTrx() {
        return $this->QtyTrx;
    }

    function getName() {
        return $this->Name;
    }

    function getSales_Desc() {
        return $this->Sales_Desc;
    }

    function getDisponible() {
        return $this->Disponible;
    }

    function getEstado() {
        return $this->Estado;
    }

// **********************
// SETTER METHODS
// **********************


    function setTxnLineID($val) {
        $this->TxnLineID = $val;
    }

    function setTimeCreated($val) {
        $this->TimeCreated = $val;
    }

    function setTimeModified($val) {
        $this->TimeModified = $val;
    }

    function setEditSequence($val) {
        $this->EditSequence = $val;
    }

    function setTxnDate($val) {
        $this->TxnDate = $val;
    }

    function setRefNumber($val) {
        $this->RefNumber = $val;
    }

    function setItemRefListID($val) {
        $this->ItemRef_ListID = $val;
    }

    function setItemRefFullName($val) {
        $this->ItemRef_FullName = $val;
    }

    function setMemo($val) {
        $this->Memo = $val;
    }

    function setMemoTrx($val) {
        $this->MemoTrx = $val;
    }

    function setNumeroTrx($val) {
        $this->NumeroTrx = $val;
    }

    function setFechaTrx($val) {
        $this->FechaTrx = $val;
    }

    function setTipoTrx($val) {
        $this->TipoTrx = $val;
    }

    function setOrigenTrx($val) {
        $this->OrigenTrx = $val;
    }

    function setDestinoTrx($val) {
        $this->DestinoTrx = $val;
    }

    function setOrigenDesc($val) {
        $this->OrigenDesc = $val;
    }

    function setDestinoDesc($val) {
        $this->DestinoDesc = $val;
    }

    function setQtyTrx($val) {
        $this->QtyTrx = $val;
    }

    function setName($val) {
        $this->Name = $val;
    }

    function setSales_Desc($val) {
        $this->Sales_Desc = $val;
    }

    function setDisponible($val) {
        $this->Disponible = $val;
    }

    function setEstado($val) {
        $this->Estado = $val;
    }

    public function initialize() {
        $this->setSchema("carrillo_dbaurora");
        $this->setSource("lotestrxtmp");
    }

    public static function find($parameters = null) {
        return parent::find($parameters);
    }

    public static function findFirst($parameters = null) {
        return parent::findFirst($parameters);
    }

    public function getSource() {
        return 'lotestrxtmp';
    }

}
